#pragma once
#include <Windows.h>

#define SE_CREATE_TOKEN_NAME_A                         "SeCreateTokenPrivilege"
#define SE_ASSIGNPRIMARYTOKEN_NAME_A                   "SeAssignPrimaryTokenPrivilege"
#define SE_LOCK_MEMORY_NAME_A                          "SeLockMemoryPrivilege"
#define SE_INCREASE_QUOTA_NAME_A                       "SeIncreaseQuotaPrivilege"
#define SE_UNSOLICITED_INPUT_NAME_A                    "SeUnsolicitedInputPrivilege"
#define SE_MACHINE_ACCOUNT_NAME_A                      "SeMachineAccountPrivilege"
#define SE_TCB_NAME_A                                  "SeTcbPrivilege"
#define SE_SECURITY_NAME_A                             "SeSecurityPrivilege"
#define SE_TAKE_OWNERSHIP_NAME_A                       "SeTakeOwnershipPrivilege"
#define SE_LOAD_DRIVER_NAME_A                          "SeLoadDriverPrivilege"
#define SE_SYSTEM_PROFILE_NAME_A                       "SeSystemProfilePrivilege"
#define SE_SYSTEMTIME_NAME_A                           "SeSystemtimePrivilege"
#define SE_PROF_SINGLE_PROCESS_NAME_A                  "SeProfileSingleProcessPrivilege"
#define SE_INC_BASE_PRIORITY_NAME_A                    "SeIncreaseBasePriorityPrivilege"
#define SE_CREATE_PAGEFILE_NAME_A                      "SeCreatePagefilePrivilege"
#define SE_CREATE_PERMANENT_NAME_A                     "SeCreatePermanentPrivilege"
#define SE_BACKUP_NAME_A                               "SeBackupPrivilege"
#define SE_RESTORE_NAME_A                              "SeRestorePrivilege"
#define SE_SHUTDOWN_NAME_A                             "SeShutdownPrivilege"
#define SE_DEBUG_NAME_A                                "SeDebugPrivilege"
#define SE_AUDIT_NAME_A                                "SeAuditPrivilege"
#define SE_SYSTEM_ENVIRONMENT_NAME_A                   "SeSystemEnvironmentPrivilege"
#define SE_CHANGE_NOTIFY_NAME_A                        "SeChangeNotifyPrivilege"
#define SE_REMOTE_SHUTDOWN_NAME_A                      "SeRemoteShutdownPrivilege"
#define SE_UNDOCK_NAME_A                               "SeUndockPrivilege"
#define SE_SYNC_AGENT_NAME_A                           "SeSyncAgentPrivilege"
#define SE_ENABLE_DELEGATION_NAME_A                    "SeEnableDelegationPrivilege"
#define SE_MANAGE_VOLUME_NAME_A                        "SeManageVolumePrivilege"
#define SE_IMPERSONATE_NAME_A                          "SeImpersonatePrivilege"
#define SE_CREATE_GLOBAL_NAME_A                        "SeCreateGlobalPrivilege"
#define SE_TRUSTED_CREDMAN_ACCESS_NAME_A               "SeTrustedCredManAccessPrivilege"
#define SE_RELABEL_NAME_A                              "SeRelabelPrivilege"
#define SE_INC_WORKING_SET_NAME_A                      "SeIncreaseWorkingSetPrivilege"
#define SE_TIME_ZONE_NAME_A                            "SeTimeZonePrivilege"
#define SE_CREATE_SYMBOLIC_LINK_NAME_A                 "SeCreateSymbolicLinkPrivilege"
#define SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME_A    "SeDelegateSessionUserImpersonatePrivilege"


#define SE_CREATE_TOKEN_NAME_W                         L"SeCreateTokenPrivilege"
#define SE_ASSIGNPRIMARYTOKEN_NAME_W                   L"SeAssignPrimaryTokenPrivilege"
#define SE_LOCK_MEMORY_NAME_W                          L"SeLockMemoryPrivilege"
#define SE_INCREASE_QUOTA_NAME_W                       L"SeIncreaseQuotaPrivilege"
#define SE_UNSOLICITED_INPUT_NAME_W                    L"SeUnsolicitedInputPrivilege"
#define SE_MACHINE_ACCOUNT_NAME_W                      L"SeMachineAccountPrivilege"
#define SE_TCB_NAME_W                                  L"SeTcbPrivilege"
#define SE_SECURITY_NAME_W                             L"SeSecurityPrivilege"
#define SE_TAKE_OWNERSHIP_NAME_W                       L"SeTakeOwnershipPrivilege"
#define SE_LOAD_DRIVER_NAME_W                          L"SeLoadDriverPrivilege"
#define SE_SYSTEM_PROFILE_NAME_W                       L"SeSystemProfilePrivilege"
#define SE_SYSTEMTIME_NAME_W                           L"SeSystemtimePrivilege"
#define SE_PROF_SINGLE_PROCESS_NAME_W                  L"SeProfileSingleProcessPrivilege"
#define SE_INC_BASE_PRIORITY_NAME_W                    L"SeIncreaseBasePriorityPrivilege"
#define SE_CREATE_PAGEFILE_NAME_W                      L"SeCreatePagefilePrivilege"
#define SE_CREATE_PERMANENT_NAME_W                     L"SeCreatePermanentPrivilege"
#define SE_BACKUP_NAME_W                               L"SeBackupPrivilege"
#define SE_RESTORE_NAME_W                              L"SeRestorePrivilege"
#define SE_SHUTDOWN_NAME_W                             L"SeShutdownPrivilege"
#define SE_DEBUG_NAME_W                                L"SeDebugPrivilege"
#define SE_AUDIT_NAME_W                               L"SeAuditPrivilege"
#define SE_SYSTEM_ENVIRONMENT_NAME_W                   L"SeSystemEnvironmentPrivilege"
#define SE_CHANGE_NOTIFY_NAME_W                        L"SeChangeNotifyPrivilege"
#define SE_REMOTE_SHUTDOWN_NAME_W                      L"SeRemoteShutdownPrivilege"
#define SE_UNDOCK_NAME_W                               L"SeUndockPrivilege"
#define SE_SYNC_AGENT_NAME_W                           L"SeSyncAgentPrivilege"
#define SE_ENABLE_DELEGATION_NAME_W                    L"SeEnableDelegationPrivilege"
#define SE_MANAGE_VOLUME_NAME_W                        L"SeManageVolumePrivilege"
#define SE_IMPERSONATE_NAME_W                          L"SeImpersonatePrivilege"
#define SE_CREATE_GLOBAL_NAME_W                        L"SeCreateGlobalPrivilege"
#define SE_TRUSTED_CREDMAN_ACCESS_NAME_W               L"SeTrustedCredManAccessPrivilege"
#define SE_RELABEL_NAME_W                              L"SeRelabelPrivilege"
#define SE_INC_WORKING_SET_NAME_W                      L"SeIncreaseWorkingSetPrivilege"
#define SE_TIME_ZONE_NAME_W                            L"SeTimeZonePrivilege"
#define SE_CREATE_SYMBOLIC_LINK_NAME_W                 L"SeCreateSymbolicLinkPrivilege"
#define SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME_W    L"SeDelegateSessionUserImpersonatePrivilege"

#define SE_CREATE_TOKEN_NAME_ID                        0x1
#define SE_ASSIGNPRIMARYTOKEN_NAME_ID                  0x2
#define SE_LOCK_MEMORY_NAME_ID                         0x4
#define SE_INCREASE_QUOTA_NAME_ID                      0x8
#define SE_UNSOLICITED_INPUT_NAME_ID                   0x10
#define SE_MACHINE_ACCOUNT_NAME_ID                     0x20
#define SE_TCB_NAME_ID                                 0x40
#define SE_SECURITY_NAME_ID                            0x80
#define SE_TAKE_OWNERSHIP_NAME_ID                      0x100
#define SE_LOAD_DRIVER_NAME_ID                         0x200
#define SE_SYSTEM_PROFILE_NAME_ID                      0x400
#define SE_SYSTEMTIME_NAME_ID                          0x800
#define SE_PROF_SINGLE_PROCESS_NAME_ID                 0x1000
#define SE_INC_BASE_PRIORITY_NAME_ID                   0x2000
#define SE_CREATE_PAGEFILE_NAME_ID                     0x4000
#define SE_CREATE_PERMANENT_NAME_ID                    0x8000
#define SE_BACKUP_NAME_ID                              0x10000
#define SE_RESTORE_NAME_ID                             0x20000
#define SE_SHUTDOWN_NAME_ID                            0x40000
#define SE_DEBUG_NAME_ID                               0x80000
#define SE_AUDIT_NAME_ID                               0x100000
#define SE_SYSTEM_ENVIRONMENT_NAME_ID                  0x200000
#define SE_CHANGE_NOTIFY_NAME_ID                       0x400000
#define SE_REMOTE_SHUTDOWN_NAME_ID                     0x800000
#define SE_UNDOCK_NAME_ID                              0x1000000
#define SE_SYNC_AGENT_NAME_ID                          0x2000000
#define SE_ENABLE_DELEGATION_NAME_ID                   0x4000000
#define SE_MANAGE_VOLUME_NAME_ID                       0x8000000
#define SE_IMPERSONATE_NAME_ID                         0x10000000
#define SE_CREATE_GLOBAL_NAME_ID                       0x20000000
#define SE_TRUSTED_CREDMAN_ACCESS_NAME_ID              0x40000000
#define SE_RELABEL_NAME_ID                             0x80000000
#define SE_INC_WORKING_SET_NAME_ID                     0x100000000
#define SE_TIME_ZONE_NAME_ID                           0x200000000
#define SE_CREATE_SYMBOLIC_LINK_NAME_ID                0x400000000
#define SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME_ID   0x800000000